[project]
name = "pomni"
version = "0.1.0"
description = "JAX Code assistant"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "google-generativeai>=0.8.5",
    "ipykernel>=6.29.5",
    "jupyter>=1.1.1",
    "keras>=3.10.0",
    "keras-hub>=0.19.0",
    "nbformat>=5.10.4",
    "pandas>=2.3.0",
    "patdb>=0.1.0",
    "pylsp-rope>=0.1.17",
    "requests>=2.32.3",
    "streamlit>=1.47.1",
    "vertexai>=1.71.1",
]

[dependency-groups]
dev = [
    "basedpyright>=1.29.2",
    "pdbpp>=0.11.6",
    "python-lsp-server>=1.12.2",
    "ruff>=0.11.12",
]
